package com.example.ch3_helloworld;

import androidx.appcompat.app.AppCompatActivity;
import android.content.res.Resources;

//Bundle = passes data bw activities and back to itself (ex: when orientation changes)
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

//MainActivity = where activity's functionality is written
//AppCompatActivity = provides functionality required by any class that uses/interacts
//    w/ other Activities used in class
public class MainActivity extends AppCompatActivity {

    //Override = tells compiler that method right under it is to be used in place of
    //    super class's method by the same name
    @Override

    //onCreate = first method executed by Activity when it's started
    //All methods must be called here to be executed
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //R.layout.activity_main = R parameter tells compiler we want to use resource
        //    from layout folder "activity_main"
        //Refers to file generated by compiler named "R.java"
        setContentView(R.layout.activity_main);

        initDisplayButton();
    }

    //private = usable only by this class
    //void = doesn't return a value
    private void initDisplayButton() {
        //findViewById = gets reference to widget on layout so it can be used by code
        Button displayButton = findViewById(R.id.buttonDisplay);
        displayButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                EditText editName = findViewById(R.id.editTextName);
                TextView textDisplay = findViewById(R.id.textViewDisplay);
                String nameToDisplay = editName.getText().toString();
                Resources res = getResources();
                //Refer to strings.xml file
                String displayString = res.getString(R.string.welcome_message, nameToDisplay);
                textDisplay.setText(displayString);
            }
        });
    }
}